version: '3.8'

services:
  px4_traj_runner:
    image: px4-traj-runner
    deploy:
      replicas: 30
      resources:
        limits:
          cpus: "2"  # Cada contenedor usa 1 CPU completa
        reservations:
          cpus: "2"  # Reserva 1 CPU por contenedor
    restart: "no"